apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: monitoring
data:
  loki-config.yaml: |
    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    ingester:
      chunk_target_size: 1048576
      max_chunks_per_query: 2000
      max_cache_size: 104857600

    schema_config:
      configs:
        - from: 2020-10-21
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h
          chunks:
            prefix: chunk_
            period: 168h

    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/index
        cache_location: /data/loki/cache
        shared_store: filesystem
      filesystem:
        directory: /data/loki/chunks

    limits_config:
      max_concurrent: 20
      max_streams_per_user: 10000
      max_entries_limit_per_query: 5000
      max_query_series: 500000

    compactor:
      working_directory: /data/loki/compactor
      shared_store: filesystem

    query_range:
      interval: 1s
      max_retries: 5
      timeout: 1m

    frontend:
      log_queries_longer_than: 5s
